version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
    - "9092:9092"
    hostname: kafka1
    environment:
      KAFKA_CREATE_TOPICS: "messages:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: localhost # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"